export { VariantPanelProvider, useVariantPanel } from './context/VariantPanelContext';
export { VARIANT_CONTROLS } from './config/variantControls';
export { DEFAULT_VARIANT_STATE, DEV_PANEL_SHORTCUT_LABEL } from './config/defaultVariantState';
export type {
  AboutCardsVariantId,
  AboutCopyVariantId,
  AboutToneVariantId,
  BackgroundContrastVariantId,
  BackgroundGridVariantId,
  BackgroundParallaxVariantId,
  BackgroundStyleVariantId,
  ContactFooterVariantId,
  ContactIntroVariantId,
  ContactLayoutVariantId,
  ContactSurfaceVariantId,
  HeroHeadlineVariantId,
  HeroResumeMode,
  HeroSupportVariantId,
  HeroVisualVariantId,
  InteractiveFeaturedVariantId,
  InteractiveIntroVariantId,
  InteractiveLegacyVariantId,
  InteractiveSurfaceVariantId,
  OptimizationAtmosphereVariantId,
  OptimizationGlassBehaviorVariantId,
  OptimizationGlassLevelVariantId,
  OptimizationGlassPauseVariantId,
  OptimizationGlassScopeVariantId,
  OptimizationGlassTransitionVariantId,
  OptimizationSurfaceVariantId,
  SkillsChipVariantId,
  SkillsIntroVariantId,
  SkillsLayoutVariantId,
  ProjectsCardVariantId,
  ProjectsIntroVariantId,
  ProjectsLayoutVariantId,
  ProjectsSurfaceVariantId,
  VariantState,
} from './config/types';
